### ISSUE TITLE
Throw error or sanitize if invalid XML characters should be serialized

### ISSUE THREAD

**Issue by dominic-simplan** [x2js/x2js#101]
There are some specific characters (such as the vertical tab, 0x0B) which are not allowed in XML, even if they are escaped as entities (https://stackoverflow.com/questions/8386970/best-practice-for-handling-vertical-tabs-and-other-invalid-xml-characters).

Using such a character will create an invalid XML and most likely thow an error in the library which is reading the XML.

It would be great if x2js could therefore throw an error if it encounters such and invalid character or provide an option to automatically remove there characters (maybe using something like this: https://stackoverflow.com/a/14801798/3049015?).

**Comment by Maxouhell** [comment]
Hi ! I don't think that it's a good idea to automatically update the content given to x2js. 
As a user, I don't want my content to be updated without my consentement, it can probably make some problems.

I'll close this issue, feel free to re-open it if necessary.

**Comment by dominic-simplan** [comment]
Thanks for your feedback.
If you don't like the idea to add an option to automatically remove invalid XML characters, I think at least the library could throw an error instead of creating an invalid XML.
Better throw an error than returning an invalid XML which will cause issues later on.
