### ISSUE TITLE
Depends on a vulnerable version of `xmldom`

### ISSUE THREAD

**Issue by s100** [x2js/x2js#104]
`x2js` depends on `xmldom@^0.1.19`. `xmldom` versions 0.4.0 or older have [this vulnerability](https://www.npmjs.com/advisories/1650). This can be remediated by updating to `xmldom@0.5.0` or later.

`xmldom` has [gone through some breaking changes](https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md) since v0.1.19... hard to say from my perspective how taxing this upgrade would be.

**Comment by jessehouwing** [comment]
It looks like the dependabot PR passes tests, that's good.

https://github.com/x2js/x2js/pull/103

**Comment by Maxouhell** [comment]
Ook sorry, I don't know why but notifications were disabled...
I will update that asap and make a new version (before the end of the week, I promise :) )

**Comment by Maxouhell** [comment]
Done ! V3.4.1
Let me know if there is any issue !

**Comment by s100** [comment]
Perfect. Thank you very much for the speedy turnaround here!
