### ISSUE TITLE
xmldom vulnerable dependency

### ISSUE THREAD

**Issue by vic6** [x2js/x2js#110]
`xmldom` has published a fix for this vulnerability in v0.7.0 under `@xml/xmldom` https://github.com/xmldom/xmldom/issues/271. Is it possible for x2js to use this new version?

**Comment by Maxouhell** [comment]
Seriously...

A mail, linkedin, whatsapp + the Pull Request notifications and all of this 20 fuck*** minutes after your PR at 11pm..
I don't know you, calm down, I do this on my free time, that's harrassment...

If you want something from somewone quickly, trust me that's not the right way. Don't ever do that again ><
