### ISSUE TITLE
Can you provide an official release for 3.4.2?

### ISSUE THREAD

**Issue by xiaowang03** [x2js/x2js#113]
Right now, the latest release is 3.2.3.

**Comment by Ruffio** [comment]
+1

**Comment by Maxouhell** [comment]
Yes without any problem, but i can't do this before monday because I don't have any computer right now.

**Comment by Maxouhell** [comment]
It's done !

3.4.2 was done on npm, but I totally forgot about GitHub. 

Mybad :)

**Comment by xiaowang03** [comment]
> It's done !
> 
> 3.4.2 was done on npm, but I totally forgot about GitHub.
> 
> Mybad :)

No problem. 
It is mainly for other colleagues if they want to verified that we are allowed to use it or not.
