### ISSUE TITLE
Type mismatch in d.ts file in regards to dom2js method

### ISSUE THREAD

**Issue by danyk2099** [x2js/x2js#116]
Hi,

the description above the dom2js method states that the domNode parameter should be of the type of Node element, but the interface in the method's signature requires a domNode with type of a Document. 

This is breaking builds in Typescript/Angular projects, since there's a type mismatch.

Suggestion: set domNode to be either solely Node, or, if it presents a problem to other users, add a pipe that defines that domNode should be a Node as well. Example: **dom2js<T>(domNode: Document | Node): T;**

Here's the current state of the definition:

 **/**
     * Transforms a DOM tree to JavaScript objects.
     * 
     * @template T
     * @param {Node} domNode
     * @returns {T}
     * 
     * @memberOf X2JS
     */
    dom2js<T>(domNode: Document): T;**

I've already added a fix in a fork and am waiting for approval: **https://github.com/x2js/x2js/pull/115**

**Comment by Maxouhell** [comment]
No need to create an issue, I've already seen your PR ;)

I'll merge that asap.

**Comment by danyk2099** [comment]
Oh, that's great! Thanks :)
