### ISSUE TITLE
take over the maintainer

### ISSUE THREAD

**Issue by gulping** [x2js/x2js#65]
@sandersaares 

Hi, I'm @gulping`<gulping.gulpin@gmail.com>`.

I probably can take over the maintainer.

- pros
    - I'll use this library for *next few years* on the job, so I'll maintain this during that period.
- cons
    - Not familiar to OSS moderating
    - Non native speaker of English

thanks.

**Comment by sandersaares** [comment]
Hi! Thank for the offer! @Maxouhell has already indicated interest in taking over maintainership, so I will leave it to him to discuss how to arrange things and to see how he can best use your assistance here.

**Comment by Maxouhell** [comment]
Hi !
Yes, we already did it :)

We are working on an upgrade of the library with es6 / ESLint.

But we will be happy to have your support !
Don't hesitate to make PR / issues, we are connected every day :)

**Comment by gulping** [comment]
Oh sorry! I just read README and didn't read closed issue.
I'm glad to hear that this lib is kept on maintaining!

please close this issue :P
