### ISSUE TITLE
Missing tag 3.2.0

### ISSUE THREAD

**Issue by Nox-404** [x2js/x2js#68]
Hello,
I saw that you bumped the version number in the package.json, but there is no tag 3.2.0 there yet.

Anyway thanks for your quick merge 👍

**Comment by rtrompier** [comment]
Hi,

We did it, but it seem to have an issue with NPM.
Check here the status of the issue : https://status.npmjs.org/incidents/gbk5bjx1169j

**Comment by Nox-404** [comment]
Okay, thanks
I'll watch over this then

**Comment by rtrompier** [comment]
Should be good now ;)
