### ISSUE TITLE
Versioning inconsistencies

### ISSUE THREAD

**Issue by gknapp** [x2js/x2js#75]
Hi,

When looking at changes in the latest npm release (`v3.2.1`), the releases page shows `3.1.1` as the latest. There's no tags for any version beyond this, where as `CHANGELOG.md` only lists `3.2.0` and `3.2.2`. 

Could some clean-up and synchronization be done please?

**Comment by Maxouhell** [comment]
Yes !
I'm working on the 4.0 typescript version, this is why I havn't cleaned it before.

I will do it next week.

**Comment by Maxouhell** [comment]
All of them are showing 3.2.3 now.

I'm closing this issue !
Don't hesitate to reopen it if needed.

Maxime.
